name: CI/CD Pipeline Deploy to AWS/EC2 - website

run-name: ${{ github.actor }} | Deploy to AWS/EC2 🚀
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world!'


